esquelvende/core/urls.py
from django.conf.urls import url

from .views import login_user, logout_user, signup_user, home, about_us, faq

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^signup/$', signup_user),
    url(r'^login/$', login_user, name='login'),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^about-us/$', about_us),
    url(r'^faq/$', faq),
]

esquelvende/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    phone = models.IntegerField(default=None)
    avatar = models.ImageField(upload_to='avatar/',
                               default='avatar/default.jpg')

esquelvende/users/forms.py
# -- coding: utf-8 --
import StringIO

from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from PIL import Image

from .models import User, UserProfile


class FormRegister(forms.ModelForm):
    password2 = forms.CharField(widget=forms.PasswordInput(attrs = {'class': 'form-control', 'placeholder': u'Confirmar contraseña'}),)

    def __init__(self, *args, **kwargs):
        super(FormRegister, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['password'].widget  = forms.PasswordInput(attrs = {'class': 'form-control', 'placeholder': u'Contraseña'})
        self.fields['username'].widget  = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Nombre de usuario'})
        self.fields['first_name'].widget= forms.TextInput(attrs = {'class': 'form-control','placeholder': 'Nombre'})
        self.fields['last_name'].widget = forms.TextInput(attrs = {'class': 'form-control','placeholder': 'Apellido'})
        self.fields['email'].widget     = forms.TextInput(attrs = {'class': 'form-control','placeholder': 'Email'})
        
    class Meta:
        model = User
        help_texts = {
            'username': None,
        }
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if (email and
                User.objects.filter(email=email).exclude(username=username)
                            .exists()):
            raise forms.ValidationError(u'Email ya esta en uso')
        return email

    def password_matched(self):
        if self.data['password'] != self.data['password2']:
            self.errors['password'] = {u"Contraseñas no coinciden"}
            return False
        else:
            return True

    def is_valid(self):
        valid = super(FormRegister,self).is_valid()
        password_matched = self.password_matched()
        if valid and password_matched:
            return True
        else:
            return False


class FormEditUser(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(FormEditUser, self).__init__(*args, **kwargs)
        # self.fields['first_name'].required = True
        # self.fields['last_name'].required = True
        # self.fields['password'].widget  = forms.PasswordInput(attrs = {'class': 'form-control input-cstm', 'placeholder': u'Contraseña'})
        # self.fields['username'].widget  = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Nombre de usuario'})
        self.fields['first_name'].widget= forms.TextInput(attrs = {'class': 'form-control input-cstm','placeholder': 'Nombre'})
        self.fields['last_name'].widget = forms.TextInput(attrs = {'class': 'form-control input-cstm','placeholder': 'Apellido'})
        self.fields['email'].widget     = forms.TextInput(attrs = {'class': 'form-control input-cstm','placeholder': 'Email'})

    class Meta:
        model = User
        fields = ('last_name', 'first_name', 'email')

class FormEditUserProfile(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(FormEditUserProfile, self).__init__(*args, **kwargs)
        self.fields['phone'].widget = forms.TextInput(attrs = {'class': 'form-control input-cstm','placeholder': 'Celular'})

    class Meta:
        model = UserProfile
        fields = ('phone',)

class FormAvatar(forms.ModelForm):

    avatar = forms.ImageField(label="avatar")
    # , widget = forms.HiddenInput()
    class Meta:
        model = UserProfile
        fields = ('avatar',)

    # def clean_avatar(self):
    #     image_field = self.cleaned_data.get('avatar')
    #     image_file = StringIO.StringIO(image_field.read())
    #     image = Image.open(image_file)
    #     w, h = image.size
    #     image = image.resize((w, h), Image.ANTIALIAS)
    #     image_file = StringIO.StringIO()
    #     image.save(image_file, 'JPEG', quality=90)
    #     image_field.file = image_file
    #     return image_field


class FormLogin(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(FormLogin, self).__init__(*args, **kwargs)
        self.fields['username'].widget=forms.TextInput(attrs = {'class': 'form-control input-cstm', 
                                                                'placeholder': 'Nombre de usuario'})
        self.fields['username'].label = ""
        
        self.fields['password'].widget=forms.PasswordInput(attrs = {'class': 'form-control input-cstm', 
                                                                    'placeholder': u'Contraseña'})
        self.fields['password'].label = "¿Olvidó su contraseña?"

esquelvende/users/templates/form/form-edit-profile.html
<form method="POST" action="" enctype="multipart/form-data">
{% csrf_token %}

<div class="avatar-container">
    <label for="id_avatar" class="avatar rounded-circle" style="background-image: url(/media/{{ user.userprofile.avatar }})">              
        <div class="overlay rounded-circle text-center">
            <div class="text"><i class="fa fa-camera"></i></div>
        </div>
    </label>
    <input type="file" name="avatar" id="id_avatar">
</div>

<div class="row">

    <div class="col">
        
        <div class="form-group">
        {{ form.first_name }}
        </div>
        {% if form.first_name.errors %}
        {% for error in form.first_name.errors %}
        <div class="alert alert-danger">
        {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>

    <div class="col">
        <div class="form-group">
        {{ form.last_name }}
        </div>
        {% if form.last_name.errors %}
        {% for error in form.last_name.errors %}
        <div class="alert alert-danger">
        {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>  
    
</div>
    
    <div class="form-group">
    {{ form_profile.phone }}
    </div>
    {% if form_profile.phone.errors %}
    {% for error in form_profile.phone.errors %}
        <div class="alert alert-danger">
    {{ error }}
    </div>
    {% endfor %}
    {% endif %}

    <div class="form-group">
    {{ form.email }}
    </div>
    {% if form.email.errors %}
    {% for error in form.email.errors %}
    <div class="alert alert-danger">
    {{ error }}
    </div>
    {% endfor %}
    {% endif %}
    
{% comment %} {{ form_avatar.as_p }} {% endcomment %}

<button type="submit">Enviar</button>
</form>